name: Deploy static content to Pages

on:
  push:
    branches: ['master']
    paths:
      - '.github/workflows/client.yml'
      - 'ui-client/**'

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: 'ui-client'
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: |
          cd ui-client
          bun install
          bun run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ui-client/dist
          cname: wholecoiners.club
