name: Deploy static content to Pages

on:
  push:
    branches: ['master']
    paths:
      - '.github/workflows/client.yml'
      - 'ui-client/**'

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: 'ui-client'
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - uses: oven-sh/setup-bun@v1
      - run: |
          supabase link --project-ref $SUPABASE_PROJECT_ID
          supabase db start
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

      - run: |
          cd ui-client
          bun install
          bun run gen:schema
          bun run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ui-client/dist
