name: Supabase
on:
  push:
    branches: [master]
    paths:
      - 'supabase/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1

      - run: |
          supabase link --project-ref $SUPABASE_PROJECT_ID
          supabase db push
          supabase functions deploy on-new-block
          supabase functions deploy validate-address
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
